name: volume-nextjs
services:
  node:
    type: node:10
    globals:
      yarn: latest
    ssl: false
    port: 3000
proxy:
  node:
    - volume-nextjs.lndo.site:3000
tooling:
  yarn:
    service: node
  develop:
    service: node
    cmd: yarn dev
